kafka:
  consumer:
    config:
      bootstrap.servers: kafka:9092
      group.id: '0'
    topics:
      - upstream1
      - upstream2
    batch_size: 1
  producer:
    config:
      bootstrap.servers: kafka:9092
    topic: downstream1
database:
  connection: 'postgresql://postgres:password@db:5432/postgres'
flask:
  jwt_secret_key: test
  secret_key: test
  username: test
  password: test
